// Optional lane timing overrides keep one shared set while allowing lane-specific reps and send-offs.
let laneTimingGroups=[];
function laneTimingOverrides(rep){try{const value=JSON.parse(rep.dataset.laneOverrides||'{}');return value&&typeof value==='object'?value:{}}catch{return {}}}
function laneTimingSetOverrides(rep,value){rep.dataset.laneOverrides=JSON.stringify(value||{})}
function laneTimingSeconds(rep,lane,pool){const override=rep.laneOverrides?.[lane]||{},count=override.count===''||override.count===undefined?+rep.count||0:+override.count||0,interval=override.interval===undefined||override.interval===''?rep.interval:override.interval;return intervalSeconds(rep.transition||'2:00')+count*(intervalSeconds(interval||'')||(+rep.distance||0)*(pool==='25'?.9:1.05))}
function laneTimingBlockSeconds(block,lane,pool,parentRepeat=1){const repeat=parentRepeat*(+block.repeat||1);return blockItems(block).reduce((total,item)=>total+(isRepItem(item)?repeat*laneTimingSeconds(item,lane,pool):laneTimingBlockSeconds(item,lane,pool,repeat)),0)}
function laneTimingTotal(set,lane){return(set.blocks||[]).reduce((total,block)=>total+laneTimingBlockSeconds(block,lane,set.pool||'25'),0)}
function laneTimingPanel(){let panel=$('.lane-timing-panel');if(panel)return panel;panel=document.createElement('section');panel.className='lane-timing-panel';$('#sticky-totals').insertAdjacentElement('afterend',panel);return panel}
function renderLaneTiming(){const panel=laneTimingPanel();panel.hidden=blockEditorMode;if(blockEditorMode)return;panel.innerHTML=`<div class="lane-timing-head"><strong>LANE TIMING</strong><button type="button" class="outline lane-add-group">+ Add Lane</button></div><p class="lane-timing-note">Set lane-specific reps or intervals on any set line. Blank override fields use the standard set-line values.</p><div class="lane-time-totals">${laneTimingGroups.length?laneTimingGroups.map(lane=>`<div class="lane-time-total"><span>${escapeHtml(lane)}</span><strong>${formatEstimate(laneTimingTotal(currentSet(),lane))}</strong></div>`).join(''):'<span class="lane-timing-note">Add lanes to compare their total workout times.</span>'}</div>`;$('.lane-add-group',panel).onclick=()=>{const name=window.prompt('Lane name',`Lane ${laneTimingGroups.length+1}`)?.trim();if(!name||laneTimingGroups.includes(name))return;laneTimingGroups.push(name);renderLaneTiming();markDirty()}}
function openLaneOverrides(rep){if(!laneTimingGroups.length){toast('Add a lane in Lane Timing first.');return}let dialog=$('#lane-overrides-dialog');if(!dialog){dialog=document.createElement('dialog');dialog.id='lane-overrides-dialog';dialog.className='lane-overrides-dialog';dialog.innerHTML='<form method="dialog"><h2>Lane Timing Overrides</h2><p>Leave either field blank to use this set line’s standard value.</p><div class="lane-override-grid"></div><div class="dialog-actions"><button value="cancel" class="ghost">Cancel</button><button value="default" class="primary lane-overrides-save">Save Lane Timing</button></div></form>';document.body.append(dialog)}const values=laneTimingOverrides(rep),grid=$('.lane-override-grid',dialog);grid.innerHTML=laneTimingGroups.map(lane=>`<label><span>${escapeHtml(lane)}</span><input class="lane-override-count" data-lane="${escapeHtml(lane)}" type="number" min="0" placeholder="Reps" value="${escapeHtml(values[lane]?.count??'')}" /><input class="lane-override-interval" data-lane="${escapeHtml(lane)}" inputmode="text" placeholder="Interval" value="${escapeHtml(values[lane]?.interval??'')}" /></label>`).join('');$('.lane-overrides-save',dialog).onclick=event=>{event.preventDefault();const next={};laneTimingGroups.forEach(lane=>{const count=[...grid.querySelectorAll('.lane-override-count')].find(field=>field.dataset.lane===lane).value.trim(),interval=[...grid.querySelectorAll('.lane-override-interval')].find(field=>field.dataset.lane===lane).value.trim();if(count||interval)next[lane]={...(count?{count:+count}:{}),...(interval?{interval:normalizeInterval(interval)}:{})}});laneTimingSetOverrides(rep,next);dialog.close();markDirty();updateTotals();renderLaneTiming()};dialog.showModal()}
function addLaneTimingButton(rep){const controls=$('.rep-controls',rep);if(!controls||$('.lane-timing-button',controls))return;const button=document.createElement('button');button.type='button';button.className='lane-timing-button';button.textContent='Lanes';button.title='Set lane timing overrides';button.onclick=()=>openLaneOverrides(rep);controls.prepend(button)}
const addRepWithLaneTiming=addRep;
addRep=function(reps,data={}){const rep=addRepWithLaneTiming(reps,data);laneTimingSetOverrides(rep,data.laneOverrides||{});addLaneTimingButton(rep);return rep};
const readRepWithLaneTiming=readRep;
readRep=function(rep){const value=readRepWithLaneTiming(rep),overrides=laneTimingOverrides(rep);return Object.keys(overrides).length?{...value,laneOverrides:overrides}:value};
const currentSetWithLaneTiming=currentSet;
currentSet=function(){return {...currentSetWithLaneTiming(),laneGroups:[...laneTimingGroups]}};
const loadSetWithLaneTiming=loadSet;
loadSet=function(set){laneTimingGroups=Array.isArray(set.laneGroups)?[...set.laneGroups]:[];loadSetWithLaneTiming(set);document.querySelectorAll('.rep').forEach(addLaneTimingButton);renderLaneTiming()};
const setBlockEditorModeWithLaneTiming=setBlockEditorMode;
setBlockEditorMode=function(enabled){setBlockEditorModeWithLaneTiming(enabled);renderLaneTiming()};
document.addEventListener('input',event=>{if(event.target.closest?.('.rep'))setTimeout(renderLaneTiming)},true);
document.querySelectorAll('.rep').forEach(addLaneTimingButton);renderLaneTiming();
