const $=(selector,root=document)=>root.querySelector(selector);
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
let toastTimer;
function toast(message){const area=$('#toast');area.textContent=message;area.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>area.classList.remove('show'),3200)}
function requestDelete(message,action,options={}){if(window.confirm(message))action()}
const defaultDualEvents=[['200 Medley Relay','relay'],['200 Freestyle','individual'],['200 IM','individual'],['50 Freestyle','individual'],['100 Butterfly','individual'],['100 Freestyle','individual'],['500 Freestyle','individual'],['200 Freestyle Relay','relay'],['100 Backstroke','individual'],['100 Breaststroke','individual'],['400 Freestyle Relay','relay']];
const dualMeetKey='lane-lines-dual-meet-v1';
function defaultDualMeet(){return {type:'dual',teamA:'Team A',teamB:'Team B',teamC:'Team C',individualPoints:'6,4,3,2,1',relayPoints:'8,4,2',events:defaultDualEvents.map(([name,type],index)=>({id:`standard-${index}`,name,type,places:[]}))}}
function dualMeet(){try{const stored=JSON.parse(localStorage.getItem(dualMeetKey)||'null');if(!stored||!Array.isArray(stored.events))return defaultDualMeet();return {...defaultDualMeet(),...stored,type:stored.type==='double-dual'?'double-dual':'dual'}}catch{return defaultDualMeet()}}
function saveDualMeet(value){localStorage.setItem(dualMeetKey,JSON.stringify(value))}
function dualPointList(value){return String(value||'').split(',').map(point=>Number(point.trim())).filter(point=>Number.isFinite(point)&&point>=0)}
function dualMeetScore(value){const individual=dualPointList(value.individualPoints),relay=dualPointList(value.relayPoints),pairs=value.type==='double-dual'?[['a','b'],['a','c'],['b','c']]:[['a','b']];return pairs.map(pair=>{const score={pair,a:0,b:0};value.events.forEach(event=>{const points=event.type==='relay'?relay:individual;(event.places||[]).filter(team=>pair.includes(team)).forEach((team,index)=>{if(team===pair[0])score.a+=points[index]||0;else score.b+=points[index]||0})});return score})}
function renderDualMeet(){const value=dualMeet(),scores=dualMeetScore(value),names={a:value.teamA.trim()||'Team A',b:value.teamB.trim()||'Team B',c:value.teamC.trim()||'Team C'},teams=value.type==='double-dual'?['a','b','c']:['a','b'];$('#dual-meet-type').value=value.type;$('#dual-team-a').value=value.teamA;$('#dual-team-b').value=value.teamB;$('#dual-team-c').value=value.teamC;$('#dual-team-c-label').hidden=value.type!=='double-dual';$('#dual-individual-points').value=value.individualPoints;$('#dual-relay-points').value=value.relayPoints;$('#dual-meet-note').textContent=value.type==='double-dual'?'Enter the top 8 individual finishes and top 5 relay finishes. Each order is scored as three simultaneous head-to-head duals.':'The starting schedule is 6–4–3–2–1 for individual events and 8–4–2 for relays. Change either list to match your league.';$('#dual-scoreboard').className=`dual-scoreboard${value.type==='double-dual'?' double-dual-scoreboard':''}`;$('#dual-scoreboard').innerHTML=scores.map(score=>`<div><span>${escapeHtml(names[score.pair[0]])} vs ${escapeHtml(names[score.pair[1]])}</span><strong>${score.a} — ${score.b}</strong></div>`).join('');const area=$('#dual-meet-events');area.innerHTML='';value.events.forEach((event,eventIndex)=>{const points=event.type==='relay'?dualPointList(value.relayPoints):dualPointList(value.individualPoints),placeCount=value.type==='double-dual'?points.length+(event.type==='relay'?2:3):points.length,places=Array.from({length:placeCount},(_,place)=>place),card=document.createElement('section');card.className='dual-event';card.innerHTML=`<div class="dual-event-head"><div><h2>${escapeHtml(event.name)}</h2><small>${event.type==='relay'?'Relay':'Individual'} event</small></div><button class="ghost dual-remove-event" type="button" title="Remove event">×</button></div><table class="dual-places"><thead><tr><th>Place</th><th>Points</th><th>Finishing team</th></tr></thead><tbody>${places.map(place=>`<tr><td>${place+1}</td><td class="dual-points">${value.type==='double-dual'?'Pairwise':points[place]}</td><td><select data-dual-event="${eventIndex}" data-dual-place="${place}"><option value="">— No score —</option>${teams.map(team=>`<option value="${team}"${event.places?.[place]===team?' selected':''}>${escapeHtml(names[team])}</option>`).join('')}</select></td></tr>`).join('')}</tbody></table>`;$('.dual-remove-event',card).onclick=()=>{value.events.splice(eventIndex,1);saveDualMeet(value);renderDualMeet()};area.append(card)})}
function readDualMeetSettings(){const value=dualMeet();value.type=$('#dual-meet-type').value;value.teamA=$('#dual-team-a').value;value.teamB=$('#dual-team-b').value;value.teamC=$('#dual-team-c').value;value.individualPoints=$('#dual-individual-points').value;value.relayPoints=$('#dual-relay-points').value;saveDualMeet(value);return value}
function openDualMeetScoring(){renderDualMeet()}
$('#reset-dual-meet').onclick=()=>{const value=dualMeet();value.events.forEach(event=>event.places=[]);saveDualMeet(value);renderDualMeet()};
$('#add-dual-event').onclick=()=>{const name=window.prompt('Event name');if(!name?.trim())return;const type=window.confirm('Is this a relay event? Select OK for relay or Cancel for individual.')?'relay':'individual',value=dualMeet();value.events.push({id:`custom-${Date.now()}`,name:name.trim(),type,places:[]});saveDualMeet(value);renderDualMeet()};
$('#add-dual-diving').onclick=()=>{const value=dualMeet();if(value.events.some(event=>event.name==='1 m Diving')){toast('1 m Diving is already on this score sheet.');return}value.events.splice(4,0,{id:`diving-${Date.now()}`,name:'1 m Diving',type:'individual',places:[]});saveDualMeet(value);renderDualMeet()};
document.addEventListener('change',event=>{const field=event.target.closest?.('#dual-meet-type,#dual-team-a,#dual-team-b,#dual-team-c,#dual-individual-points,#dual-relay-points');if(field){readDualMeetSettings();renderDualMeet();return}const select=event.target.closest?.('select[data-dual-event]');if(!select)return;const value=dualMeet(),entry=value.events[Number(select.dataset.dualEvent)];if(!entry)return;entry.places[Number(select.dataset.dualPlace)]=select.value;saveDualMeet(value);renderDualMeet()});
renderDualMeet();
